apiVersion: v1
kind: Namespace
metadata:
  name: h4v15
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: html-app
  name: html-service
  namespace: h4v15
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: html-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: html-app
  name: html-deployment
  namespace: h4v15
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: html-app
  template:
    metadata:
      labels:
        deployment: html-app
    spec:
      containers:
      - image: image: http://192.168.67.2:5000/hav1s/html.gitops-img
        imagePullPolicy: IfNotPresent
        name: html-container
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-volume
      volumes:
      - name: html-volume
