apiVersion: apps/v1
kind: Namespace
metadata:
  name: h4v15
  namespace: h4v15
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: html-app
  name: html-service
  namespace: h4v15
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: html-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: html-app
  name: html-deployment
  namespace: h4v15
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: html-app
    spec:
      containers:
      - image: localhost:5000/hav1s/html-gitops-img:v1.0.1
        imagePullPolicy: IfNotPresent
        #always -- IfNotPresent
        name: html-container
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-volume
      volumes:
      - configMap:
          name: html-configmap
        name: html-volume
