# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages

stages:
  - clone
  - deploy

steps:
  clone:
    title: Cloning main repository...
    type: git-clone
    stage: clone
    arguments:
      repo: https://github.com/hav1s/html-gitops.git
      git: github
      revision: main

  deploy:
    title: Deploying to Staging using Kustomize...
    type: freestyle
    stage: deploy
    working_directory: ${{clone}}
    arguments:
      image: my-html-app
      commands:
        - kubectl config use-context docker-desktop
        - kubectl apply -k overlays/staging