# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - ../../base
namePrefix: staging-
commonLabels:
  variant: staging
bases:
- ../../base
patchesStrategicMerge:
  - configMap.yaml

