apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: html-app
spec:
  replicas: 2  # Scaling up for production
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
        - name: html-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: html-configmap
