namePrefix: production-
resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    variant: production
patches:
- path: deployment.yaml
- path: configMap.yaml