apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    deployment: html-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: html-app
    spec:
      containers:
        - name: html-container
          image: hav1s/html-gitops-img:v1.0.1
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: html-configmap
