apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    deployment: html-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      deployment: html-app
  template:
    metadata:
      labels:
        deployment: html-app
    spec:
      containers:
        - name: html-container
          image: http://192.168.67.2:5000/hav1s/html.gitops-img
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          # imagePullPolicy: Always
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
