apiVersion: v1
kind: Service
metadata:
  name: html-service
  labels:
    app: html-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: html-app
