apiVersion: v1
kind: Service
metadata:
  name: html-service
  labels:
    app: html-app
spec:
  project: html-devops-proj
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: html-app
