apiVersion: v1
kind: Service
metadata:
  name: html-service
  labels:
    deployment: html-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    deployment: html-app
