name: Test Workflow Dispatch

on:
    push:
        branches:
            - main

    workflow_dispatch:
        inputs:
            environment:
                description: "The Environmenr To Deploy To"
                required: true
                default: "prod"
                type: choice
                options:
                    - prod
                    - staging
                    - dev

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Run Hello Workflow
          run: echo Hello Workflow
    
    build:
        runs-on: ubuntu-latest
        needs: unit-tests
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
    
    prod-deploy:
        if: startsWith(github.event.head_commit.message, 'feat:') || startsWith(github.event.head_commit.message, 'fix:')
        runs-on: ubuntu-latest
        needs: [unit-tests, build]
        permissions:
            id-token: write
            contents: read
        steps:
        - name: Prod Deploy
          if: ${{ github.event.inputs.environment == 'prod' }} 
          run: echo Prod Deployed

    staging-deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
        - name: Staging Deploy
          if: ${{ github.event.inputs.environment == 'staging' }} 
          run: echo Staging Deployedd
    
    dev-deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
        - name: Dev Deply
          if: ${{ github.event.inputs.environment == 'dev' }} 
          run: echo Dev Deployed

    





# jobs:

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Deploy to Production
#         if: ${{ github.event.inputs.environment == 'prod' }}
#         run: echo "Deploying to Production..."

#       - name: Deploy to Staging
#         if: ${{ github.event.inputs.environment == 'staging' }}
#         run: echo "Deploying to Staging..."

#       - name: Deploy to Development
#         if: ${{ github.event.inputs.environment == 'dev' }}
#         run: echo "Deploying to Development..."